import Head from 'next/head'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'
import goup from '../assets/IMG-20220901-WA0020.jpg'
import Image from 'next/image'
import { Project, Skill, Social } from '../typings'
import { GetStaticProps } from 'next'
import { fetchSocials } from '../utils/fetchSocials'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchProjects } from '../utils/fetchProjects'


type Props = {
  skills:Skill[];
  projects:Project[];
  socials:Social[];
};

export default function Home({skills,projects,socials}: Props) {
  return (
    <div className=' bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0  scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/80 scrollbar-thin '>
      <Head>
        <title>Kamal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header socials={socials}/>
      {/* Hero */}
      <section id='hero' className=' snap-center'>
        <Hero/>
      </section>
      {/* About */}
      <section id='about' className=' snap-center'>
        <About/>
      </section>
      {/* Experience */}
      <section id='exp' className=' snap-center'>
        <WorkExperience/>
      </section>
      {/* Skills */}
      <section id='skills' className=' snap-start'>
        <Skills skills={skills}/>
      </section>
      {/* Projects */}
      <section id='projects' className=' snap-start'>
        <Projects projects={projects}/>
      </section>
      {/* Contact Me */}
      <section id='contact' className=' snap-start'>
        <Contact/>
      </section>
      <Link href='#hero'>
        <footer className=' sticky bottom-5 w-full cursor-pointer'>
          <div className=' flex items-center justify-center'>
            <Image src={goup} alt='/' className='w-10 h-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer'/>
          </div>
        </footer>
      </Link>
    </div>
  )
};

export const getStaticProps: GetStaticProps  = async ()=>{
  const socials: Social[] = await fetchSocials();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();

  return{
    props:{
      socials,
      skills,
      projects,
    },
    revalidate:10,
  }
}
